run test

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -5,8 +5,42 @@ on:
     branches: [ "master" ]
 
 jobs:
+
+
+  
+  unit-tests:
+    runs-on: ubuntu-latest
+    environment: prod
+    permissions:
+      contents: read
+      packages: write
+    
+    steps:
+    - uses: actions/checkout@v4
+    
+    - name: Log in to GitHub Container Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.TOKEN }}
+    
+    - name: Pull the Docker image
+      run: |
+        docker pull ghcr.io/dolce-zampa/webservice:latest
+    
+    - name: Run unit tests
+      run: |
+        docker run --rm ghcr.io/dolce-zampa/webservice:latest vendor/bin/phpunit --testdox --colors=always > test-results.txt || true
+        cat test-results.txt
+        # Check if there are any failed tests
+        if grep -q "FAILURES!" test-results.txt; then
+          exit 1
+        fi
+        
   build:
     runs-on: ubuntu-latest
+    needs: unit-tests
     environment: prod
     permissions:
       contents: read
@@ -31,7 +65,7 @@ jobs:
         docker push ghcr.io/dolce-zampa/webservice:latest
 
   deploy:
-      needs: build
+      needs: build 
       runs-on: ubuntu-latest
       environment: prod
       steps:
